version: '3.8'

services:
  app:
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - payment-processor

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - payment-processor

networks:
  payment-processor:
    external: true
