version: '3.8'

x-app-config: &app-config
  build: .
  depends_on:
    redis:
      condition: service_healthy
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PAYMENT_API_URL=http://payment-processor-default:8001
    - PAYMENT_API_FALLBACK_URL=http://payment-processor-fallback:8002
  networks:
    - app
    - payment-processor
  deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "125MB"

services:
  jvpayments-1:
    <<: *app-config

  jvpayments-2:
    <<: *app-config

  haproxy:
    image: haproxy:alpine
    ports:
      - "9999:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - jvpayments-1
      - jvpayments-2
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
